apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    environment: prod 
spec:
  containers:
    - name: nginx-pod-1
      image: nginx
      env :
        - name: environment
          value: prod
        - name: github_url
          value: https://github.com/devopshimanshu/kubernetes_practise.git
      args: ["$(environment)"]
      ports:
        - containerPort: 80
    - name: tomcat
      image: tomcat
      ports:
        - containerPort: 8080
  initContainers:
    - name: initcontainer1
      image: busybox:1.28
      args: ["sleep":"60"]