apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-example
spec:
  replicas: 2
  selector:
    matchExpressions:
      - key: type
        operator: In
        values:
          - production
  template:
    metadata:
      labels:
        type: production
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80